#! /bin/sh
#  Requires the latest ffmpeg, compiled as per these instructions
#  https://ffmpeg.org/trac/ffmpeg/wiki/UbuntuCompilationGuide
#
ffmpeg -f x11grab -r 30 -s 1920x1080 -i :0.0 -vcodec libx264  -threads 0 video.mkv
